// Generated by pikto apply. Do not edit path data by hand: sources, licenses and operations are in .pikto/provenance.json.
// Colour comes from currentColor, so existing state classes (.source-state.ready, .claim-rejected, …) keep working.
const PATHS = {
  // ph:magnifying-glass (Phosphor 2.1.1, MIT): Discover stage
  'discover': `<path stroke="none" d="m21.53 20.47-4.69-4.69a8.26 8.26 0 1 0-1.06 1.06l4.69 4.69a.75.75 0 0 0 1.06-1.06M3.75 10.5a6.75 6.75 0 1 1 6.75 6.75 6.76 6.76 0 0 1-6.75-6.75"/>`,
  // ph:stack (Phosphor 2.1.1, MIT): Build stage
  'build': `<path stroke="none" d="M21.65 16.13a.75.75 0 0 1-.27 1.02l-9 5.25a.75.75 0 0 1-.76 0l-9-5.25a.75.75 0 0 1 .76-1.3L12 20.88l8.63-5.03a.75.75 0 0 1 1.02.27m-1.02-4.77L12 16.38l-8.62-5.03a.75.75 0 0 0-.75 1.3l9 5.25a.75.75 0 0 0 .75 0l9-5.25a.75.75 0 1 0-.75-1.3M2.25 7.5a.75.75 0 0 1 .38-.65l8.99-5.25a.75.75 0 0 1 .76 0l9 5.25a.75.75 0 0 1 0 1.3l-9 5.25a.75.75 0 0 1-.76 0l-9-5.25a.75.75 0 0 1-.37-.65m2.24 0L12 11.88l7.51-4.38L12 3.12Z"/>`,
  // ph:cube (Phosphor 2.1.1, MIT): Materialize stage
  'materialize': `<path stroke="none" d="m20.97 6.2-8.25-4.51a1.49 1.49 0 0 0-1.44 0L3.03 6.2a1.5 1.5 0 0 0-.78 1.32v8.96a1.5 1.5 0 0 0 .78 1.31l8.25 4.52a1.49 1.49 0 0 0 1.44 0l8.25-4.52a1.5 1.5 0 0 0 .78-1.31V7.52a1.5 1.5 0 0 0-.78-1.32M12 3l7.53 4.13L12 11.25 4.47 7.13ZM3.75 8.44l7.5 4.1v8.04l-7.5-4.1Zm9 12.14v-8.03l7.5-4.11v8.04Z"/>`,
  // ph:info (Phosphor 2.1.1, MIT): Provenance legend
  'legend': `<path stroke="none" d="M12 2.25A9.75 9.75 0 1 0 21.75 12 9.76 9.76 0 0 0 12 2.25m0 18A8.25 8.25 0 1 1 20.25 12 8.26 8.26 0 0 1 12 20.25m1.5-3.75a.75.75 0 0 1-.75.75 1.5 1.5 0 0 1-1.5-1.5V12a.75.75 0 0 1 0-1.5 1.5 1.5 0 0 1 1.5 1.5v3.75a.75.75 0 0 1 .75.75m-3-8.63A1.13 1.13 0 1 1 11.63 9a1.13 1.13 0 0 1-1.13-1.12"/>`,
  // ph:check-circle (Phosphor 2.1.1, MIT): confirmed / covered / selected / locally available
  'confirmed': `<path stroke="none" d="M16.28 9.22a.75.75 0 0 1 0 1.06l-5.25 5.25a.75.75 0 0 1-1.06 0l-2.25-2.25a.75.75 0 0 1 1.06-1.06l1.72 1.72 4.72-4.72a.75.75 0 0 1 1.06 0M21.75 12A9.75 9.75 0 1 1 12 2.25 9.76 9.76 0 0 1 21.75 12m-1.5 0A8.25 8.25 0 1 0 12 20.25 8.26 8.26 0 0 0 20.25 12"/>`,
  // ph:circle-half (Phosphor 2.1.1, MIT): partial claim / locally weak source
  'partial': `<path stroke="none" d="M12 2.25A9.75 9.75 0 1 0 21.75 12 9.76 9.76 0 0 0 12 2.25m.75 1.53a8 8 0 0 1 1.5.29v15.87a8 8 0 0 1-1.5.28Zm3 .87a8.2 8.2 0 0 1 1.5.99v12.72a8.2 8.2 0 0 1-1.5.99ZM3.75 12a8.26 8.26 0 0 1 7.5-8.22v16.44A8.26 8.26 0 0 1 3.75 12m15 4.74V7.26a8.23 8.23 0 0 1 0 9.48"/>`,
  // ph:circle-dashed (Phosphor 2.1.1, MIT): available, not taken up
  'available': `<path stroke="none" d="M9.02 3.47a.75.75 0 0 1 .54-.91 9.76 9.76 0 0 1 4.88 0 .75.75 0 0 1-.19 1.47.8.8 0 0 1-.19-.02 8.26 8.26 0 0 0-4.12 0 .75.75 0 0 1-.92-.54m-3.98 1.7a9.75 9.75 0 0 0-2.43 4.22.75.75 0 0 0 1.44.4 8.25 8.25 0 0 1 2.06-3.57.75.75 0 0 0-1.07-1.05m-.99 9.04a.75.75 0 1 0-1.44.4 9.76 9.76 0 0 0 2.43 4.22.75.75 0 0 0 1.07-1.05 8.26 8.26 0 0 1-2.06-3.57m10.01 5.78a8.25 8.25 0 0 1-4.12 0 .75.75 0 1 0-.38 1.45 9.76 9.76 0 0 0 4.88 0 .75.75 0 0 0-.38-1.45m6.81-6.3a.75.75 0 0 0-.92.52 8.24 8.24 0 0 1-2.06 3.57.75.75 0 1 0 1.07 1.05 9.75 9.75 0 0 0 2.44-4.22.75.75 0 0 0-.53-.92m-.92-3.9a.75.75 0 0 0 1.44-.4 9.75 9.75 0 0 0-2.43-4.22.75.75 0 1 0-1.07 1.06 8.25 8.25 0 0 1 2.06 3.56"/>`,
  // ph:x-circle (Phosphor 2.1.1, MIT): rejected / missing
  'rejected': `<path stroke="none" d="M15.53 9.53 13.06 12l2.47 2.47a.75.75 0 0 1-1.06 1.06L12 13.06l-2.47 2.47a.75.75 0 0 1-1.06-1.06L10.94 12 8.47 9.53a.75.75 0 0 1 1.06-1.06L12 10.94l2.47-2.47a.75.75 0 0 1 1.06 1.06M21.75 12A9.75 9.75 0 1 1 12 2.25 9.76 9.76 0 0 1 21.75 12m-1.5 0A8.25 8.25 0 1 0 12 20.25 8.26 8.26 0 0 0 20.25 12"/>`,
  // ph:question (Phosphor 2.1.1, MIT): unresolved claim
  'unresolved': `<path stroke="none" d="M13.13 16.88A1.13 1.13 0 1 1 12 15.75a1.13 1.13 0 0 1 1.12 1.13M12 6.75c-2.07 0-3.75 1.51-3.75 3.38v.37a.75.75 0 0 0 1.5 0v-.37c0-1.03 1.01-1.88 2.25-1.88s2.25.84 2.25 1.88S13.24 12.01 12 12a.75.75 0 0 0-.75.75v.75a.75.75 0 0 0 1.5 0v-.07c1.71-.31 3-1.68 3-3.31 0-1.86-1.68-3.38-3.75-3.37M21.75 12A9.75 9.75 0 1 1 12 2.25 9.76 9.76 0 0 1 21.75 12m-1.5 0A8.25 8.25 0 1 0 12 20.25 8.26 8.26 0 0 0 20.25 12"/>`,
  // ph:plus-circle (Phosphor 2.1.1, MIT): proposed claim / candidate source
  'proposed': `<path stroke="none" d="M12 2.25A9.75 9.75 0 1 0 21.75 12 9.76 9.76 0 0 0 12 2.25m0 18A8.25 8.25 0 1 1 20.25 12 8.26 8.26 0 0 1 12 20.25M16.5 12a.75.75 0 0 1-.75.75h-3v3a.75.75 0 0 1-1.5 0v-3h-3a.75.75 0 0 1 0-1.5h3v-3a.75.75 0 0 1 1.5 0v3h3a.75.75 0 0 1 .75.75"/>`,
  // ph:arrow-up-right (Phosphor 2.1.1, MIT): opens an external source
  'external': `<path stroke="none" d="M18.75 6v9.75a.75.75 0 0 1-1.5 0V7.81L6.53 18.53a.75.75 0 0 1-1.06-1.06L16.19 6.75H8.25a.75.75 0 0 1 0-1.5H18a.75.75 0 0 1 .75.75"/>`,
} as const;

export type IconName = keyof typeof PATHS;

export const icon = (name: IconName, size = 16): string =>
  `<svg class="icon icon-${name}" viewBox="0 0 24 24" width="${size}" height="${size}" fill="currentColor" stroke="currentColor" aria-hidden="true" focusable="false" style="vertical-align:-0.125em;flex:none">${PATHS[name]}</svg>`;
