/**
 * "Unentdeckt" on the proposal page: the doorway datasets of the largest groups of one category,
 * shown as their generated covers. Static HTML, written into index.html by
 * scripts/proposal-hero.ts, so the page needs no script and no request to show them.
 *
 * The selection is the doorway rule (src/doorway.ts), nothing hand-picked. The text says which
 * category it covers and when it was measured, so three books never read as "the least used
 * datasets of the whole catalogue".
 */
import type { DataForm } from './atlas-spec';
import type { Doorway } from './doorway';

export const HERO_START = '<!-- unentdeckt:start (generated by scripts/proposal-hero.ts) -->';
export const HERO_END = '<!-- unentdeckt:end -->';

const FORM_DE: Readonly<Record<DataForm, string>> = {
  point: 'Punkte', line: 'Linien', area: 'Flächen', mixed: 'gemischte Geometrie', raster: 'Kartendienst / Datei',
  series: 'Zeitreihe', table: 'Tabelle', unknown: 'Form unbekannt',
};

const SUB_DE: Readonly<Record<string, string>> = {
  'Road traffic': 'Strassenverkehr', Cycling: 'Velo', Walking: 'Fussverkehr', Parking: 'Parkieren',
  'Public transport': 'Öffentlicher Verkehr', Other: 'Weiteres',
};
const CATEGORY_DE: Readonly<Record<string, string>> = { 'Mobility & Transport': 'Mobilität & Verkehr' };

export const subcategoryDe = (name: string): string => SUB_DE[name] ?? name;
export const categoryDe = (name: string): string => CATEGORY_DE[name] ?? name;

const count = (value: number): string => new Intl.NumberFormat('de-CH').format(value);

/** The doorway reason in German, from the structured figures (never by translating the English prose). */
export function reasonDe(doorway: Doorway, form: DataForm): string {
  const records = doorway.dataset.recordsCount ?? 0;
  const ready = `Bereit: ${count(records)} ${records === 1 ? 'Eintrag' : 'Einträge'}, ${FORM_DE[form]}.`;
  if (doorway.basis === 'usage' && doorway.downloadsPerMonth !== undefined) {
    const reuses = doorway.reuses ?? 0;
    const reuse = reuses === 0 ? 'keine dokumentierte Nutzung' : `${reuses} dokumentierte ${reuses === 1 ? 'Nutzung' : 'Nutzungen'}`;
    return `${ready} Am wenigsten genutzt in der Gruppe: rund ${count(Math.round(doorway.downloadsPerMonth))} Downloads pro Monat, ${reuse}.`;
  }
  return `${ready} Am vollständigsten beschrieben in dieser Gruppe; die Nutzung ist nicht vergleichbar.`;
}

export interface HeroPick {
  group: string;
  groupSize: number;
  glyph: string;
  doorway: Doorway;
  form: DataForm;
  cover: string;
  catalogueUrl: string;
}

export interface HeroMeta {
  category: string;
  categorySize: number;
  groupCount: number;
  asOf: string;
  libraryUrl: string;
}

const esc = (value: string): string => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const dateDe = (iso: string): string => { const [y, m, d] = iso.split('-'); return `${d}.${m}.${y}`; };

export function heroHtml(picks: readonly HeroPick[], meta: HeroMeta): string {
  const books = picks.map((pick, i) => `
          <li class="book b${i + 1}">
            <a class="cover-link" href="${esc(pick.catalogueUrl)}" aria-label="${esc(pick.doorway.dataset.title)} im Katalog öffnen">${pick.cover}</a>
            <p class="group">${pick.glyph}${esc(subcategoryDe(pick.group))} <span>· ${pick.groupSize} Datensätze</span></p>
            <h3><a href="${esc(pick.catalogueUrl)}">${esc(pick.doorway.dataset.title)}</a></h3>
            <p class="why">${esc(reasonDe(pick.doorway, pick.form))}</p>
          </li>`).join('');
  return `${HERO_START}
    <section id="unentdeckt" class="unentdeckt">
      <div class="wrap">
        <p class="eyebrow">Unentdeckt · ${esc(categoryDe(meta.category))}</p>
        <h2>Bereit, aber wenig genutzt</h2>
        <p class="intro">Aus den ${picks.length} grössten Gruppen im Thema ${esc(categoryDe(meta.category))}: je ein Datensatz, der sauber beschrieben ist, echte Einträge hat und in seiner Gruppe am seltensten heruntergeladen wird. Ausgewählt nach einer festen Regel, nicht von Hand.</p>
        <ul class="books">${books}
        </ul>
        <p class="shelf-link"><a class="btn ghost" href="${esc(meta.libraryUrl)}">Alle ${meta.categorySize} Datensätze zu ${esc(categoryDe(meta.category))} als Regal ansehen</a></p>
        <p class="fine">Die Umschläge sind aus den Metadaten und einer kleinen echten Stichprobe erzeugt (Karte, Zeitreihe oder Spaltentypen), kein Bild des Herausgebers; ihre Beschriftung ist englisch. Regel: mindestens 10 Einträge, bekannte Form und eine Beschreibung; darunter die wenigsten Downloads pro Monat seit Veröffentlichung, bevorzugt ohne dokumentierte Nutzung. Bisher nur ${esc(categoryDe(meta.category))} (${meta.groupCount} Gruppen); Stand ${dateDe(meta.asOf)}.</p>
      </div>
    </section>
    ${HERO_END}`;
}

/** Replace the generated block, or insert it right after the page hero on first run. */
export function spliceHero(page: string, block: string): string {
  const start = page.indexOf(HERO_START);
  const end = page.indexOf(HERO_END);
  if (start >= 0 && end > start) return page.slice(0, start) + block + page.slice(end + HERO_END.length);
  const anchor = page.indexOf('<section id="heute">');
  if (anchor < 0) throw new Error('index.html: no generated block and no <section id="heute"> to insert before');
  return `${page.slice(0, anchor)}${block}\n\n    ${page.slice(anchor)}`;
}
